language: node_js

node_js: 16

os:
  - osx
  - windows

install: npm i

cache:
  directories:
    - node_modules
    - '%USERPROFILE%\.electron'

script:
  npm run make

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: out
  edge: true
  on:
    tags: true
