language: node_js

os:
  - osx
  - windows

install: yarn

cache:
  directories:
    - node_modules
    - '%USERPROFILE%\.electron'

script:
  yarn make

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: out
  edge: true
  on:
    tags: true
