language: node_js

node_js: 16

os:
  - osx
  - windows

install: npm i

cache:
  directories:
    - node_modules

script:
  npm run make

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: out/make/zip/**/*.zip
  edge: true
  on:
    tags: true
